Word.destroy_all

word_hash = [
  { wordname: "Airplane", strength: "easy" },
  { wordname: "Ears", strength: "easy" },
  { wordname: "Piano", strength: "easy" },
  { wordname: "Angry", strength: "easy" },
  { wordname: "Elephant", strength: "easy" },
  { wordname: "Pinch", strength: "easy" },
  { wordname: "Baby", strength: "easy" },
  { wordname: "Fish", strength: "easy" },
  { wordname: "Reach", strength: "easy" },
  { wordname: "Ball", strength: "easy" },
  { wordname: "Flick", strength: "easy" },
  { wordname: "Remote", strength: "easy" },
  { wordname: "Baseball", strength: "easy" },
  { wordname: "Football", strength: "easy" },
  { wordname: "Roll", strength: "easy" },
  { wordname: "Hashketball", strength: "easy" },
  { wordname: "Fork", strength: "easy" },
  { wordname: "Bounce", strength: "easy" },
  { wordname: "Giggle", strength: "easy" },
  { wordname: "Scissors", strength: "easy" },
  { wordname: "Cat", strength: "easy" },
  { wordname: "Golf", strength: "easy" },
  { wordname: "Skip", strength: "easy" },
  { wordname: "Chicken", strength: "easy" },
  { wordname: "Guitar", strength: "easy" },
  { wordname: "Sneeze", strength: "easy" },
  { wordname: "Chimpanzee", strength: "easy" },
  { wordname: "Hammer", strength: "easy" },
  { wordname: "Spin", strength: "easy" },
  { wordname: "Clap", strength: "easy" },
  { wordname: "Happy", strength: "easy" },
  { wordname: "Spoon", strength: "easy" },
  { wordname: "Cough", strength: "easy" },
  { wordname: "Horns", strength: "easy" },
  { wordname: "Stomp", strength: "easy" },
  { wordname: "Cry", strength: "easy" },
  { wordname: "Joke", strength: "easy" },
  { wordname: "Stop", strength: "easy" },
  { wordname: "Dog", strength: "easy" },
  { wordname: "Mime", strength: "easy" },
  { wordname: "Tail", strength: "easy" },
  { wordname: "Drink", strength: "easy" },
  { wordname: "Penguin", strength: "easy" },
  { wordname: "Toothbrush", strength: "easy" },
  { wordname: "Drums", strength: "easy" },
  { wordname: "Phone", strength: "easy" },
  { wordname: "Wiggle", strength: "easy" },
  { wordname: "Duck", strength: "easy" },
  { wordname: "Photographer", strength: "easy" },
  { wordname: "Archer", strength: "medium" },
  { wordname: "Ghost", strength: "medium" },
  { wordname: "Rock star", strength: "medium" },
  { wordname: "Balance beam", strength: "medium" },
  { wordname: "Haircut", strength: "medium" },
  { wordname: "Shoelaces", strength: "medium" },
  { wordname: "Ballet", strength: "medium" },
  { wordname: "Halo", strength: "medium" },
  { wordname: "Sick", strength: "medium" },
  { wordname: "Balloon", strength: "medium" },
  { wordname: "Hiccup", strength: "medium" },
  { wordname: "Singer", strength: "medium" },
  { wordname: "Banana peel", strength: "medium" },
  { wordname: "Hot dog", strength: "medium" },
  { wordname: "Skateboard", strength: "medium" },
  { wordname: "Book", strength: "medium" },
  { wordname: "Hungry", strength: "medium" },
  { wordname: "Slippery", strength: "medium" },
  { wordname: "Braces", strength: "medium" },
  { wordname: "Hurt", strength: "medium" },
  { wordname: "Soccer", strength: "medium" },
  { wordname: "Button", strength: "medium" },
  { wordname: "Ice skating", strength: "medium" },
  { wordname: "Strong", strength: "medium" },
  { wordname: "Car", strength: "medium" },
  { wordname: "Karate", strength: "medium" },
  { wordname: "Stubbed toe", strength: "medium" },
  { wordname: "Cheers", strength: "medium" },
  { wordname: "Ladder", strength: "medium" },
  { wordname: "Sunshine", strength: "medium" },
  { wordname: "Clown", strength: "medium" },
  { wordname: "Light bulb", strength: "medium" },
  { wordname: "Surprise", strength: "medium" },
  { wordname: "Dinosaur", strength: "medium" },
  { wordname: "Limbo", strength: "medium" },
  { wordname: "Swing", strength: "medium" },
  { wordname: "Disco", strength: "medium" },
  { wordname: "Macarena", strength: "medium" },
  { wordname: "Sword", strength: "medium" },
  { wordname: "Dizzy", strength: "medium" },
  { wordname: "Paint", strength: "medium" },
  { wordname: "Tap dance", strength: "medium" },
  { wordname: "Fart", strength: "medium" },
  { wordname: "Pirate", strength: "medium" },
  { wordname: "Wheelbarrow", strength: "medium" },
  { wordname: "Fishing", strength: "medium" },
  { wordname: "Read", strength: "medium" },
  { wordname: "Wizard of Oz", strength: "medium" },
  { wordname: "Gallop", strength: "medium" },
  { wordname: "River dance", strength: "medium" },
  { wordname: "Birthday ", strength: "hard" },
  { wordname: "Hedgehog", strength: "hard" },
  { wordname: "Pizza", strength: "hard" },
  { wordname: "Blanket", strength: "hard" },
  { wordname: "Helicopter", strength: "hard" },
  { wordname: "President", strength: "hard" },
  { wordname: "Bright", strength: "hard" },
  { wordname: "Hurricane", strength: "hard" },
  { wordname: "Rainbow", strength: "hard" },
  { wordname: "Bump", strength: "hard" },
  { wordname: "Kite", strength: "hard" },
  { wordname: "Rollercoaster", strength: "hard" },
  { wordname: "Christmas", strength: "hard" },
  { wordname: "Light", strength: "hard" },
  { wordname: "Shadow", strength: "hard" },
  { wordname: "Coffee", strength: "hard" },
  { wordname: "Magic", strength: "hard" },
  { wordname: "Shopping", strength: "hard" },
  { wordname: "Cradle", strength: "hard" },
  { wordname: "Makeup", strength: "hard" },
  { wordname: "Shuffle", strength: "hard" },
  { wordname: "Deer", strength: "hard" },
  { wordname: "Marriage", strength: "hard" },
  { wordname: "Slice", strength: "hard" },
  { wordname: "Drool", strength: "hard" },
  { wordname: "Mash", strength: "hard" },
  { wordname: "Slip n’ slide", strength: "hard" },
  { wordname: "Electric Slide", strength: "hard" },
  { wordname: "Measure", strength: "hard" },
  { wordname: "Smear", strength: "hard" },
  { wordname: "Excitement", strength: "hard" },
  { wordname: "Mirror", strength: "hard" },
  { wordname: "Spider", strength: "hard" },
  { wordname: "Fight Club", strength: "hard" },
  { wordname: "Monster", strength: "hard" },
  { wordname: "The Lion King", strength: "hard" },
  { wordname: "Firefighter", strength: "hard" },
  { wordname: "Motorcycle", strength: "hard" },
  { wordname: "Trampoline", strength: "hard" },
  { wordname: "Flashlight", strength: "hard" },
  { wordname: "Nightmare", strength: "hard" },
  { wordname: "Waterfall", strength: "hard" },
  { wordname: "Garden", strength: "hard" },
  { wordname: "Nosey", strength: "hard" },
  { wordname: "Window", strength: "hard" },
  { wordname: "Giraffe", strength: "hard" },
  { wordname: "Overwhelmed", strength: "hard" },
  { wordname: "Yo-yo", strength: "hard" },
  { wordname: "Heavy", strength: "hard" },
  { wordname: "Pancakes", strength: "hard" }
]

word_hash.each { |word| Word.create(word)}
